---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
# These are dev dependencies, they are here to be picked up
# by renv
if (FALSE) {
  library(devtools)
  library(usethis)
  library(covr)
  library(pkgdown)
  library(styler)
}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# IPCWJK

<!-- badges: start -->
<!-- badges: end -->

```{r, echo = FALSE, output = "asis"}
descr <- packageDescription("IPCWJK")
descr$Title
```

```{r, echo = FALSE, output = "asis"}
descr <- packageDescription("IPCWJK")
descr$Description
```

The documentation is available at 
[https://github.com/IDEN-Project-UAS-Darmstadt/IPCWJK](
  https://github.com/IDEN-Project-UAS-Darmstadt/IPCWJK)

## Installation

You can install the development version of IPCWJK like so:

``` r
# With remotes
remotes::install_github("IDEN-Project-UAS-Darmstadt/IPCWJK")
# With pak (recommended for speed)
pak::pkg_install("IDEN-Project-UAS-Darmstadt/IPCWJK")
```

## Example

```{r data_weights}
library(survival)
tau <- 80
df <- veteran[, c("time", "status", "trt")]
newdata <- data.frame(trt = c(1, 2))

# Calculation of IPCW weights at tau
w <- ipcw_weights(df, tau, time_var = "time", status_var = "status")
hist(w,
  breaks = 30,
  xlab = "IPCW Weight", col = "lightblue", border = "grey"
)
```

```{r data_weights}
# Fit a log-logistic survival model
survreg_fit <- survreg(Surv(time, status) ~ trt,
  data = df,
  dist = "loglogistic"
)
# This provides you with an Wald CI on the logit scale:
pred_fun <- deltamethod_from_model(survreg_fit, tau = tau)
pred_fun(newdata)

# Fit a logitIPCW model
library(mets)
logipcw_fit <- logitIPCW(Event(time, status) ~ trt, time = tau, data = df)
predfun_logit <- deltamethod_from_model(logipcw_fit, tau = tau)
pred_fun(newdata)

# IPCW Logistic Regression
fit <- ipcw_logistic_regression(df,
  tau = tau, time_var = "time",
  status_var = "status"
)
predict(fit, newdata)

# IPCW XGBoost Classifier
fit <- ipcw_xgboost(df, tau = tau, time_var = "time", status_var = "status")
predict(fit, newdata)
```

# Development

Restore the development environment with:

```r
renv::restore()
```

then use anything available in the `devtools` package to develop the package.

```r
library(devtools)
document() # to update documentation and roxygen functionality
load_all() # to load the package functions for development
build_readme() # to update the README
test() # to run tests
check() # to check the package
covr::package_coverage() # to check code coverage
styler::style_pkg() # to style the code
lint() # to check the code for linting issues
```
